services:
    password_reset_email_sender:
        class: LaVestima\HannaAgency\MessageBundle\Sender\PasswordResetEmailSender
        autowire: true

    password_reser_email_helper:
        class: LaVestima\HannaAgency\MessageBundle\Sender\Helper\PasswordResetEmailHelper
        autowire: true
