services:
    ReCaptcha\ReCaptcha:
        arguments:
            $secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'
            $requestMethod: '@ReCaptcha\RequestMethod'

    ReCaptcha\RequestMethod: '@ReCaptcha\RequestMethod\CurlPost'
    ReCaptcha\RequestMethod\CurlPost: null
    ReCaptcha\RequestMethod\Curl: null

# Uncomment this line if you want to inject the site key to all your Twig templates.
# You can also inject the "google_recaptcha_site_key" container parameter to your controllers.
#twig:
#    globals:
#        google_recaptcha_site_key: '%google_recaptcha_site_key%'
