#!/bin/bash
rm src/Migrations/Version*

docker exec -it ejas_mysql mysql -u root -ptoor -h localhost -e "DROP DATABASE IF EXISTS ejas; CREATE DATABASE ejas CHARACTER SET utf8 COLLATE utf8_general_ci;"

docker exec -it ejas_php php ejas/bin/console make:migration
docker exec -it ejas_php php ejas/bin/console doctrine:migrations:migrate --no-interaction

docker exec -it ejas_php php ejas/bin/console doctrine:fixtures:load --append

docker exec -it ejas_php php ejas/bin/console faker:create:product 25
docker exec -it ejas_php php ejas/bin/console faker:create:order 25
