#!/bin/bash

docker exec -it ejas_mysql mysql -u root -ptoor -h localhost -e "DROP DATABASE IF EXISTS ejas; CREATE DATABASE ejas CHARACTER SET utf8 COLLATE utf8_general_ci;"

docker exec -it ejas php bin/console doctrine:migrations:migrate --no-interaction

docker exec -it ejas php bin/console doctrine:fixtures:load --append

docker exec -it ejas php bin/console faker:create:product 20
docker exec -it ejas php bin/console faker:create:order 10
