#!/bin/bash

clear

echo "-----------------------------------------------"
echo -e "\e[1mAccess Control\e[0m"
phpunit src/LaVestima/HannaAgency/AccessControlBundle/Tests/Controller/LoginControllerTest.php

echo "-----------------------------------------------"
echo -e "\e[1mInfrastructure\e[0m"
phpunit src/LaVestima/HannaAgency/InfrastructureBundle/Tests/Controller/Helper/CrudHelperTest.php

echo "-----------------------------------------------"
echo -e "\e[1mOrder\e[0m"
phpunit src/LaVestima/HannaAgency/OrderBundle/Tests/Controller/OrderControllerTest.php

echo "-----------------------------------------------"
echo -e "\e[1mUser Management\e[0m"
phpunit src/LaVestima/HannaAgency/UserManagementBundle/Tests/Controller/Crud/UserCrudControllerTest.php
