app:
    resource: "@AppBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation

admin:
    resource: "@AppBundle/Controller/AdminController.php"
    prefix:   /admin
    type:     annotation

super_admin:
    resource: "@AppBundle/Controller/SuperAdminController.php"
    prefix:   /super_admin
    type:     annotation

login:
    resource: "@AppBundle/Controller/SecurityController.php"
    prefix:   /security
    type:     annotation

faker:
    resource: "@AppBundle/Controller/FakerController.php"
    prefix:   /faker
    type:     annotation

logout:
    path: /logout