security:
    providers:
        db_provider:
            entity:
                class: LaVestima\HannaAgency\UserManagementBundle\Entity\Users
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            security: true
            anonymous: true
            form_login:
                login_path: access_control_login
                check_path: access_control_login
                default_target_path: homepage_homepage
#                always_use_default_target_path: true
                success_handler: authentication_handler
                failure_handler: authentication_handler
                use_forward: false
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: homepage_homepage
            provider: db_provider
#            access_denied_url: /login

#        secured_area:
##            http_basic: ~
##            pattern: ^/admin
#            form_login:
#                csrf_token_generator: security.csrf.token_manager

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        LaVestima\HannaAgency\UserManagementBundle\Entity\Users:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_GUEST: IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_USER: ROLE_GUEST
        ROLE_CUSTOMER: ROLE_USER
        ROLE_ADMIN: ROLE_CUSTOMER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account_activation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/user_settings, roles: ROLE_GUEST }

        - { path: ^/invoice, roles: ROLE_USER }
        - { path: ^/order, roles: ROLE_CUSTOMER }
        - { path: ^/export, roles: ROLE_USER }

        - { path: ^/customer, roles: ROLE_ADMIN }
        - { path: ^/login_attempt, roles: ROLE_ADMIN }

        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/export/pdf/order_list, roles: ROLE_ADMIN }

        - { path: ^/, roles: ROLE_CUSTOMER }
