services:
    country_crud_controller:
        class: LaVestima\HannaAgency\LocationBundle\Controller\Crud\CountryCrudController
        autowire: true

    city_crud_controller:
        class: LaVestima\HannaAgency\LocationBundle\Controller\Crud\CityCrudController
        autowire: true
