services:
    _defaults:
        autowire: true

    city_crud_controller:
        class: LaVestima\HannaAgency\LocationBundle\Controller\Crud\CityCrudController

    country_crud_controller:
        class: LaVestima\HannaAgency\LocationBundle\Controller\Crud\CountryCrudController

    LaVestima\HannaAgency\LocationBundle\Controller\Crud\CityCrudControllerInterface:
        alias: city_crud_controller

    LaVestima\HannaAgency\LocationBundle\Controller\Crud\CountryCrudControllerInterface:
        alias: country_crud_controller
