services:
#    infrastructure.example:
#        class: LaVestima\HannaAgency\InfrastructureBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    crud_controller:
        class: LaVestima\HannaAgency\InfrastructureBundle\Controller\CrudController
        arguments: ['@doctrine', '@security.token_storage']