order_list:
    path: /order/list/{type}
    defaults: { _controller: OrderBundle:Order:list, type: '' }

order_deleted_list:
    path: /order/list/{type}
    defaults: { _controller: OrderBundle:Order:list, type: 'deleted' }

#order_deleted_list:
#    path: /order/deleted_list
#    defaults: { _controller: OrderBundle:Order:deletedList }

order_show:
    path: /order/show/{pathSlug}
    defaults: { _controller: OrderBundle:Order:show, pathSlug: '' }

order_new:
    path: /order/new
    defaults: { _controller: OrderBundle:Order:new }

order_delete:
    path: /order/delete/{pathSlug}
    defaults: { _controller: OrderBundle:Order:delete, pathSlug: '' }

order_restore:
    path: /order/restore/{pathSlug}
    defaults: { _controller: OrderBundle:Order:restore, pathSlug: '' }

order_placement_new:
    path: /order_placement/new
    defaults: { _controller: OrderBundle:OrderPlacement:new }

order_placement_summary:
    path: /order_placement/summary
    defaults: { _controller: OrderBundle:OrderPlacement:summary }