services:
#    order.example:
#        class: LaVestima\HannaAgency\OrderBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    order_crud_controller:
        class: LaVestima\HannaAgency\OrderBundle\Controller\Crud\OrderCrudController
        arguments: ['@doctrine', '@security.token_storage']

    order_product_crud_controller:
        class: LaVestima\HannaAgency\OrderBundle\Controller\Crud\OrderProductCrudController
        arguments: ['@doctrine', '@security.token_storage']

    order_status_crud_controller:
        class: LaVestima\HannaAgency\OrderBundle\Controller\Crud\OrderStatusCrudController
        arguments: ['@doctrine', '@security.token_storage']