services:
    _defaults:
        autowire: true

    LaVestima\HannaAgency\OrderBundle\Controller\OrderController:

    LaVestima\HannaAgency\OrderBundle\Controller\Async\OrderAsyncController:

    order_crud_controller:
        class: LaVestima\HannaAgency\OrderBundle\Controller\Crud\OrderCrudController

    order_product_crud_controller:
        class: LaVestima\HannaAgency\OrderBundle\Controller\Crud\OrderProductCrudController

    order_status_crud_controller:
        class: LaVestima\HannaAgency\OrderBundle\Controller\Crud\OrderStatusCrudController

    LaVestima\HannaAgency\OrderBundle\Form\PlaceOrderType:
        tags: [form.type]

    LaVestima\HannaAgency\OrderBundle\Controller\Crud\OrderCrudControllerInterface:
        alias: order_crud_controller

    LaVestima\HannaAgency\OrderBundle\Controller\Crud\OrderProductCrudControllerInterface:
        alias: order_product_crud_controller

    LaVestima\HannaAgency\OrderBundle\Controller\Crud\OrderStatusCrudControllerInterface:
        alias: order_status_crud_controller
