#invoice_homepage:
#    path:     /
#    defaults: { _controller: InvoiceBundle:Default:index }

invoice_list:
    path: /invoice/list
    defaults: { _controller: InvoiceBundle:Invoice:list }

invoice_new:
    path: /invoice/new
    defaults: { _controller: InvoiceBundle:Invoice:new }
