invoice_list:
    path: /invoice/list
    defaults: { _controller: InvoiceBundle:Invoice:list }

invoice_show:
    path: /invoice/show/{invoiceId}
    defaults: { _controller: InvoiceBundle:Invoice:show, invoiceId: 0 }
    requirements:
        invoiceId: '\d+'

invoice_new:
    path: /invoice/new
    defaults: { _controller: InvoiceBundle:Invoice:new }
