invoice_list:
    path: /invoice/list
    defaults: { _controller: InvoiceBundle:Invoice:list }

invoice_deleted_list:
    path: /invoice/deleted_list
    defaults: { _controller: InvoiceBundle:Invoice:deletedList }

invoice_show:
    path: /invoice/show/{pathSlug}
    defaults: { _controller: InvoiceBundle:Invoice:show, pathSlug: '' }

invoice_delete:
    path: /invoice/delete/{invoiceId}
    defaults: { _controller: InvoiceBundle:Invoice:delete, invoiceId: 0 }

invoice_new:
    path: /invoice/new
    defaults: { _controller: InvoiceBundle:Invoice:new }

invoice_async_list:
    path: /invoice/async/list
    defaults: { _controller: InvoiceBundle:Async\InvoiceAsync:list }
    options:
        expose: true

invoice_async_deleted_list:
    path: /invoice/async/deleted_list
    defaults: { _controller: InvoiceBundle:Async\InvoiceAsync:deletedList }
    options:
        expose: true
