services:
    _defaults:
        autowire: true

    LaVestima\HannaAgency\InvoiceBundle\Controller\InvoiceController:

    invoice_crud_controller:
        class: LaVestima\HannaAgency\InvoiceBundle\Controller\Crud\InvoiceCrudController

    invoice_product_crud_controller:
        class: LaVestima\HannaAgency\InvoiceBundle\Controller\Crud\InvoiceProductCrudController
