services:
#    invoice.example:
#        class: LaVestima\HannaAgency\InvoiceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    invoice_crud_controller:
        class: LaVestima\HannaAgency\InvoiceBundle\Controller\Crud\InvoiceCrudController
        autowire: true

    invoice_product_crud_controller:
        class: LaVestima\HannaAgency\InvoiceBundle\Controller\Crud\InvoiceProductCrudController
        autowire: true
