services:
#    customer.example:
#        class: LaVestima\HannaAgency\CustomerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    customer_crud_controller:
        class: LaVestima\HannaAgency\CustomerBundle\Controller\Crud\CustomerCrudController
        arguments: ['@doctrine', '@security.token_storage']