access_control_login:
    path: /login
    defaults: { _controller: AccessControlBundle:Login:index }

access_control_register:
    path: /register
    defaults: { _controller: AccessControlBundle:Register:index }

access_control_account_activation:
    path: /account_activation/{activationToken}
    defaults: { _controller: AccessControlBundle:AccountActivation:index, activationToken: '' }

access_control_forgot_password:
    path: /forgot_password
    defaults: { _controller: AccessControlBundle:ForgotPassword:index }

access_control_email_sent:
    path: /forgot_password/email_sent
    defaults: { _controller: AccessControlBundle:ForgotPassword:emailSent }

access_control_reset_password:
    path: /reset_password/{resetPasswordToken}
    defaults: { _controller: AccessControlBundle:ResetPassword:index, resetPasswordToken: '' }

access_control_login_attempt_list:
    path: /login_attempt/list
    defaults: { _controller: AccessControlBundle:LoginAttempt:list }

access_control_login_attempt_async_list:
    path: /login_attempt/async/list
    defaults: { _controller: AccessControlBundle:Async\LoginAttemptAsync:list }
    options:
        expose: true
