access_control_login:
    path: /login
    defaults: { _controller: AccessControlBundle:Login:index }

access_control_register:
    path: /register
    defaults: { _controller: AccessControlBundle:Register:index }

access_control_account_activation:
    path: /account_activation/{activationToken}
    defaults: { _controller: AccessControlBundle:AccountActivation:index, activationToken: '' }