access_control_login:
    path: /login
    defaults: { _controller: AccessControlBundle:Login:index }

access_control_register:
    path: /register
    defaults: { _controller: AccessControlBundle:Register:index }