services:
    _defaults:
        autowire: true

    LaVestima\HannaAgency\AccessControlBundle\Controller\ForgotPasswordController:

    LaVestima\HannaAgency\AccessControlBundle\Controller\ResetPasswordController:

    LaVestima\HannaAgency\AccessControlBundle\Controller\LoginAttemptController:

    LaVestima\HannaAgency\AccessControlBundle\Controller\Async\LoginAttemptAsyncController:

    token_crud_controller:
        class: LaVestima\HannaAgency\AccessControlBundle\Controller\Crud\TokenCrudController

    login_attempt_crud_controller:
        class: LaVestima\HannaAgency\AccessControlBundle\Controller\Crud\LoginAttemptCrudController

    authentication_handler:
        class: LaVestima\HannaAgency\AccessControlBundle\Handler\AuthenticationHandler

    LaVestima\HannaAgency\AccessControlBundle\Controller\Crud\LoginAttemptCrudControllerInterface:
        alias: 'login_attempt_crud_controller'

    LaVestima\HannaAgency\AccessControlBundle\Controller\Crud\TokenCrudControllerInterface:
        alias: 'token_crud_controller'
