services:
#    access_control.example:
#        class: LaVestima\HannaAgency\AccessControlBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    token_crud_controller:
        class: LaVestima\HannaAgency\AccessControlBundle\Controller\Crud\TokenCrudController
        arguments: ['@doctrine']