user_list:
    path: /user/list
    defaults: { _controller: UserManagementBundle:User:list }

user_deleted_list:
    path: /user/deleted_list
    defaults: { _controller: UserManagementBundle:User:deletedList }

user_show:
    path: /user/show/{pathSlug}
    defaults: { _controller: UserManagementBundle:User:show, pathSlug: '' }

user_new:
    path: /user/new
    defaults: { _controller: UserManagementBundle:User:new }

user_setting_index:
    path: /user_settings/
    defaults: { _controller: UserManagementBundle:UserSetting:index }

user_customer_new:
    path: /user_customer/new
    defaults: { _controller: UserManagementBundle:UserCustomer:new }

user_async_list:
    path: /user/async/list
    defaults: { _controller: UserManagementBundle:Async\UserAsync:list }
    options:
        expose: true

user_async_deleted_list:
    path: /user/async/deleted_list
    defaults: { _controller: UserManagementBundle:Async\UserAsync:deletedList }
    options:
        expose: true
