user_list:
    path: /user/list
    defaults: { _controller: UserManagementBundle:User:list }

user_show:
    path: /user/show/{pathSlug}
    defaults: { _controller: UserManagementBundle:User:show, pathSlug: '' }

user_setting_index:
    path: /user_settings/
    defaults: { _controller: UserManagementBundle:UserSetting:index }
