services:
    _defaults:
        autowire: true

    LaVestima\HannaAgency\UserManagementBundle\Controller\UserController:
#        public: true

    LaVestima\HannaAgency\UserManagementBundle\Controller\Async\UserAsyncController:

    user_crud_controller:
        class: LaVestima\HannaAgency\UserManagementBundle\Controller\Crud\UserCrudController

    role_crud_controller:
        class: LaVestima\HannaAgency\UserManagementBundle\Controller\Crud\RoleCrudController

    user_setting_crud_controller:
        class: LaVestima\HannaAgency\UserManagementBundle\Controller\Crud\UserSettingCrudController

    LaVestima\HannaAgency\UserManagementBundle\Form\UserType:
        tags: [form.type]

    LaVestima\HannaAgency\UserManagementBundle\Controller\Crud\UserCrudControllerInterface:
        alias: user_crud_controller

    LaVestima\HannaAgency\UserManagementBundle\Controller\Crud\RoleCrudControllerInterface:
        alias: role_crud_controller

    LaVestima\HannaAgency\UserManagementBundle\Controller\Crud\UserSettingCrudControllerInterface:
        alias: user_setting_crud_controller
