services:
    user_crud_controller:
        class: LaVestima\HannaAgency\UserManagementBundle\Controller\Crud\UserCrudController
        autowire: true

    role_crud_controller:
        class: LaVestima\HannaAgency\UserManagementBundle\Controller\Crud\RoleCrudController
        autowire: true

    user_setting_crud_controller:
        class: LaVestima\HannaAgency\UserManagementBundle\Controller\Crud\UserSettingCrudController
        autowire: true
