product_list:
    path: /product/list
    defaults: { _controller: ProductBundle:Product:list }

product_show:
    path: /product/show/{pathSlug}
    defaults: { _controller: ProductBundle:Product:show, pathSlug: '' }

product_new:
    path: /product/new
    defaults: { _controller: ProductBundle:Product:new }
