product_list:
    path: /product/list
    defaults: { _controller: ProductBundle:Product:list }

product_deleted_list:
    path: /product/deleted_list
    defaults: { _controller: ProductBundle:Product:deletedList }

product_show:
    path: /product/show/{pathSlug}
    defaults: { _controller: ProductBundle:Product:show, pathSlug: '' }

product_new:
    path: /product/new
    defaults: { _controller: ProductBundle:Product:new }

product_async_list:
    path: /product/async/list
    defaults: { _controller: ProductBundle:Async\ProductAsync:list }
    options:
        expose: true
