#product_homepage:
#    path:     /
#    defaults: { _controller: ProductBundle:Default:index }
product_list:
    path: /product/list
    defaults: { _controller: ProductBundle:Product:list }

product_show:
    path: /product/show/{pathSlug}
    defaults: { _controller: ProductBundle:Product:show, pathSlug: '' }
