product_list:
    path: /product/list
    defaults: { _controller: ProductBundle:Product:list }

product_deleted_list:
    path: /product/deleted_list
    defaults: { _controller: ProductBundle:Product:deletedList }

product_show:
    path: /product/show/{pathSlug}
    defaults: { _controller: ProductBundle:Product:show, pathSlug: '' }

product_delete:
    path: /product/delete/{pathSlug}
    defaults: { _controller: ProductBundle:Product:delete, pathSlug: '' }

product_new:
    path: /product/new
    defaults: { _controller: ProductBundle:Product:new }

product_edit:
    path: /product/edit/{pathSlug}
    defaults: { _controller: ProductBundle:Product:edit, pathSlug: '' }

product_async_list:
    path: /product/async/list
    defaults: { _controller: ProductBundle:Async\ProductAsync:list }
    options:
        expose: true

product_async_deleted_list:
    path: /product/async/deleted_list
    defaults: { _controller: ProductBundle:Async\ProductAsync:deletedList }
    options:
        expose: true
