services:
    _defaults:
        autowire: true

    LaVestima\HannaAgency\ProductBundle\Controller\ProductController:

    LaVestima\HannaAgency\ProductBundle\Controller\Async\ProductAsyncController:

    product_crud_controller:
        class: LaVestima\HannaAgency\ProductBundle\Controller\Crud\ProductCrudController

    size_crud_controller:
        class: LaVestima\HannaAgency\ProductBundle\Controller\Crud\SizeCrudController

    category_crud_controller:
        class: LaVestima\HannaAgency\ProductBundle\Controller\Crud\CategoryCrudController

    product_size_crud_controller:
        class: LaVestima\HannaAgency\ProductBundle\Controller\Crud\ProductSizeCrudController

    LaVestima\HannaAgency\ProductBundle\Form\ProductType:
        tags: [form.type]

    LaVestima\HannaAgency\ProductBundle\Controller\Crud\ProductCrudControllerInterface:
        alias: product_crud_controller

    LaVestima\HannaAgency\ProductBundle\Controller\Crud\SizeCrudControllerInterface:
        alias: size_crud_controller

    LaVestima\HannaAgency\ProductBundle\Controller\Crud\CategoryCrudControllerInterface:
        alias: category_crud_controller

    LaVestima\HannaAgency\ProductBundle\Controller\Crud\ProductSizeCrudControllerInterface:
        alias: product_size_crud_controller
