services:
    _defaults:
        autowire: true

    currency_crud_controller:
        class: LaVestima\HannaAgency\MoneyBundle\Controller\Crud\CurrencyCrudController

    LaVestima\HannaAgency\MoneyBundle\Controller\Crud\CurrencyCrudControllerInterface:
        alias: currency_crud_controller
